# Generated by Django 3.1.7 on 2021-05-12 04:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(help_text='Enter the book name', max_length=200, verbose_name='Book Name')),
                ('author', models.CharField(help_text="Enter the book's author name", max_length=200, verbose_name='Author')),
                ('published_by', models.CharField(max_length=200, verbose_name='Published By')),
                ('tags', models.CharField(choices=[('ACTION', 'Action'), ('THRILLER', 'Thriller'), ('ART', 'Art'), ('ROMANCE', 'Romance'), ('FAIRYTALE', 'Fairytale'), ('TRUE CRIME', 'True_crime'), ('DRAMA', 'Drama'), ('DIARY', 'Diary'), ('COMIC', 'Comic'), ('HISTORY', 'History'), ('HORROR', 'Horror')], max_length=20, verbose_name='Tag')),
                ('types', models.CharField(choices=[('Firsthand', 'Firsthand'), ('Secondhand', 'Secondhand')], default='Secondhand', max_length=30, verbose_name='Type')),
                ('price', models.DecimalField(decimal_places=2, help_text="Enter the book's price", max_digits=10, verbose_name='Price')),
                ('discount', models.CharField(choices=[('40%', '40%'), ('50%', '50%'), ('60%', '60%'), ('70%', '70%'), ('80%', '80%'), ('90%', '90%'), ('100%', '100%')], default='40%', max_length=20, verbose_name='Discount')),
                ('pin_code', models.CharField(help_text='Enter the pincode of your suitable area to sell', max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Pincode')),
                ('description', models.TextField(help_text='Please add if any extra info is there for the book', max_length=300, null=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Photo Of Book')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='custom_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=30, verbose_name='Lastname')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Phone No.')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('user_pin', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Pincode')),
                ('userlink', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_app.sell')),
            ],
        ),
    ]
